[package]
name = "untitled1"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.128"
regex = "1.10.6"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }


